export const routePaths = {
  home: '/',
  login: '/login',
  register: '/register',
  verifyOtp: '/verify-otp',
  profile: '/profile',
  movies: '/movies',
  movieDetail: '/movies/:movieId',
  cinemaDetail: '/cinema/:id',
  booking: '/booking',
  seatSelection: '/seat-selection',
  employee: {
    root: '/employee',
    pos: '/employee/pos',
    checkin: '/employee/checkin',
    schedules: '/employee/schedules',
  },
  admin: {
    root: '/admin',
    movies: '/admin/movies',
    genres: '/admin/genres',
    cinemas: '/admin/cinemas',
    concessions: '/admin/concessions',
    events: '/admin/events',
    finance: '/admin/finance',
    members: '/admin/members',
    settings: '/admin/settings',
    showtimes: '/admin/showtimes',
    staff: '/admin/staff',
    concessionSales: '/admin/concession-sales',
    payroll: '/admin/payroll',
    rooms: '/admin/rooms',
  }
};
