server.port=8080

spring.application.name=api-gateway

# Route: auth-service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173,http://localhost:5174
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=Authorization,Content-Type,Idempotency-Key,*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

spring.cloud.gateway.default-filters[0].name=DedupeResponseHeader
spring.cloud.gateway.default-filters[0].args.name=Access-Control-Allow-Origin Access-Control-Allow-Credentials
spring.cloud.gateway.default-filters[0].args.strategy=RETAIN_UNIQUE

# Route: internal user-service
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=http://localhost:8086
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[2].id=booking-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/bookings/**
# Route: promotion-service
spring.cloud.gateway.routes[3].id=promotion-service
spring.cloud.gateway.routes[3].uri=http://localhost:8087
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/admin/promotions/**,/api/admin/promotion-campaigns/**,/api/promotions/**
