package com.project.movieservice.security;

import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import io.jsonwebtoken.io.Decoders;
import io.jsonwebtoken.security.Keys;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.context.SpringBootTest;

import java.security.Key;
import java.util.Date;

import static org.junit.jupiter.api.Assertions.assertTrue;

@SpringBootTest
class JwtProviderIntegrationTest {

    @Autowired
    private JwtProvider jwtProvider;

    @Value("${jwt.secret}")
    private String jwtSecret;

    @Test
    void validateToken_ShouldReturnTrue_WhenTokenIsGeneratedByAuthServiceLogic() {
        // This mimics how Auth Service generates the token using Base64 decoding
        Key signingKey = Keys.hmacShaKeyFor(Decoders.BASE64.decode(jwtSecret));

        String realToken = Jwts.builder()
                .setSubject("testuser")
                .setIssuedAt(new Date())
                .setExpiration(new Date(System.currentTimeMillis() + 1000 * 60 * 60)) // 1 hour
                .signWith(signingKey, SignatureAlgorithm.HS256)
                .compact();

        // The Movie Service's JwtProvider should successfully validate this token
        boolean isValid = jwtProvider.validateToken(realToken);

        assertTrue(isValid, "Token generated by Auth Service logic should be valid in Movie Service");
    }
}
