CREATE TABLE IF NOT EXISTS `promotion_campaign_presentations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `campaign_public_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'DRAFT',
  `headline` varchar(180) COLLATE utf8mb4_unicode_ci NOT NULL,
  `summary` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  `cover_image_url` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cover_image_storage_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cover_image_storage_provider` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cover_image_content_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cover_image_bytes` bigint DEFAULT NULL,
  `image_alt_text` varchar(240) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `featured` tinyint(1) NOT NULL DEFAULT '0',
  `display_order` int NOT NULL DEFAULT '100',
  `show_on_home` tinyint(1) NOT NULL DEFAULT '0',
  `show_in_promotion_center` tinyint(1) NOT NULL DEFAULT '0',
  `show_in_wallet` tinyint(1) NOT NULL DEFAULT '0',
  `primary_promotion_public_id` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `published_at` datetime(6) DEFAULT NULL,
  `published_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `version` int NOT NULL DEFAULT '1',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `deleted_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_campaign_presentation_public` (`public_id`),
  UNIQUE KEY `uk_campaign_presentation_campaign` (`campaign_public_id`),
  KEY `idx_campaign_presentation_home` (`status`,`show_on_home`,`featured`,`display_order`),
  KEY `idx_campaign_presentation_center` (`status`,`show_in_promotion_center`,`featured`,`display_order`),
  KEY `idx_campaign_presentation_wallet` (`status`,`show_in_wallet`,`featured`,`display_order`),
  KEY `idx_campaign_presentation_deleted` (`deleted_at`),
  CONSTRAINT `chk_campaign_presentation_status` CHECK ((`status` in ('DRAFT','PUBLISHED','ARCHIVED'))),
  CONSTRAINT `chk_campaign_presentation_order` CHECK ((`display_order` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
