####################################################
# NOTIFICATION SERVICE - SAMPLE CONFIGURATION FILE #
####################################################
# Huong dan:
# 1) Copy file nay thanh application.properties
# 2) Dien gia tri thuc te theo moi truong local
# 3) Khong push application.properties len git

server.port=8085
spring.application.name=notification-service

# ===== Database (MySQL) =====
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${MYSQL_DATABASE:notification_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQL_USER:movieuser}
spring.datasource.password=${MYSQL_PASSWORD:moviepassword}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# ===== JPA / Hibernate =====
# update | validate | create | create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== Mail Sender Configuration (Gmail SMTP) =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===== Kafka Integration Configuration =====
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# ===== Notification Senders Configuration =====
notification.email.provider=mock
notification.mock-email.simulate-failure=false
notification.mock-email.failure-code=PROVIDER_TIMEOUT
notification.mock-email.retryable=true


# ===== JWT Configuration =====
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000