#!/bin/sh
set -eu

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE DATABASE IF NOT EXISTS auth_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS user_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS movie_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS booking_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS payment_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS notification_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS promotion_service CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS promotion_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS score_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS analytics_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON auth_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON user_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON movie_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON booking_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON payment_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON notification_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON promotion_service.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON promotion_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON score_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON analytics_db.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL
